version: '3'

services:
  db:
    image: "postgres:11"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: flybobdb
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  redis:
    image: "redis"
    volumes:
      - redis:/data
    ports:
      - "6378:6378"
  web:
    build: .
    environment:
      DATABASE_NAME: flybobdb
      DATABASE_URL: postgres://postgres:postgres@db:5432/${DATABASE_NAME}
    volumes:
      - .:/code
    ports:
      - "5000:5000"
    depends_on:
      - db
    env_file:
      - .env
volumes:
  db_data:
  redis: